[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
description = "A cryptographically secure prime number generator based on rust's own num-bigint and num-integer"
documentation = "https://docs.rs/glass_pumpkin"
edition = "2024"
homepage = "https://crates.io/crates/glass_pumpkin"
keywords = ["prime", "big", "cryptography", "generator", "number"]
license = "Apache-2.0"
name = "glass_pumpkin"
readme = "README.md"
repository = "https://github.com/mikelodder7/glass_pumpkin"
version = "2.0.0-rc1"

[dependencies]
crypto-bigint = { version = "0.7", default-features = false, features = ["alloc"] }
crypto-primes = { version = "0.7", default-features = false }
num-bigint = { version = "0.5", default-features = false, features = ["rand_core_0_10"] }
num-traits = { version = "0.2", default-features = false }
num-integer = { version = "0.1", default-features = false }
rand_core = { version = "0.10" }
getrandom = { version = "0.4", optional = true, features = ["sys_rng"] }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
rand = "0.10"

[[bench]]
name = "gen_safe_prime"
harness = false

[profile.bench]
opt-level = 3

[features]
default = ["std", "getrandom"]
std = []
# Enables methods that use `getrandom::SysRng` internally
getrandom = ["dep:getrandom"]
# Enables compilation in `no_std` environment
no_std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(cpubits, values("16", "32", "64"))'] }
